# @format

services:
  backend:
    build: ./backend
    container_name: bulk-email-backend
    ports:
      - '5000:5000'
    env_file:
      - ./backend/.env
    restart: always
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./frontend
    container_name: bulk-email-frontend
    ports:
      - '3000:3000'
    env_file:
      - ./frontend/.env
    restart: always
    depends_on:
      - backend

  postgres:
    image: postgres:15
    container_name: bulk-email-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: bulk-email-redis
    restart: always
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
